// demo-react-app/src/components/CardLabel.jsx
export default function CardLabel({ label }) {
  return (
    <span style={{
      display: 'inline-block',
      padding: '2px 8px',
      borderRadius: '10px',
      fontSize: '11px',
      fontWeight: 500,
      color: label.color,
      background: `${label.color}18`,
      lineHeight: '16px',
    }}>
      {label.text}
    </span>
  );
}

// demo-vue-app/src/components/CardLabel.vue
<script setup>
defineProps({
  label: Object,
});
</script>

<template>
  <span
    class="card-label"
    :style="{
      color: label.color,
      background: label.color + '18',
    }"
  >
    {{ label.text }}
  </span>
</template>

<style scoped>
.card-label {
  display: inline-block;
  padding: 2px 8px;
  border-radius: 10px;
  font-size: 11px;
  font-weight: 500;
  line-height: 16px;
}
</style>
