// demo-react-app/src/components/Checklist.jsx
import ChecklistItem from './ChecklistItem';

export default function Checklist({ checklist }) {
  const done = checklist.items.filter(i => i.done).length;
  const total = checklist.items.length;
  const pct = Math.round((done / total) * 100);

  return (
    <div style={{ marginTop: '10px' }}>
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: '6px',
      }}>
        <span style={{ fontSize: '11px', fontWeight: 600, color: '#6b7280' }}>
          {checklist.title}
        </span>
        <span style={{ fontSize: '11px', color: '#9ca3af' }}>
          {done}/{total}
        </span>
      </div>
      <div style={{
        height: '3px',
        background: '#e5e7eb',
        borderRadius: '2px',
        marginBottom: '6px',
        overflow: 'hidden',
      }}>
        <div style={{
          height: '100%',
          width: `${pct}%`,
          background: pct === 100 ? '#10b981' : '#6366f1',
          borderRadius: '2px',
          transition: 'width 0.2s',
        }} />
      </div>
      {checklist.items.map(item => (
        <ChecklistItem key={item.id} item={item} />
      ))}
    </div>
  );
}

// demo-vue-app/src/components/Checklist.vue
<script setup>
import { computed } from 'vue';
import ChecklistItem from './ChecklistItem.vue';

const props = defineProps({
  checklist: Object,
});

const done = computed(() => props.checklist.items.filter(i => i.done).length);
const total = computed(() => props.checklist.items.length);
const pct = computed(() => Math.round((done.value / total.value) * 100));
</script>

<template>
  <div class="checklist">
    <div class="checklist-header">
      <span class="checklist-title">{{ checklist.title }}</span>
      <span class="checklist-count">{{ done }}/{{ total }}</span>
    </div>
    <div class="progress-bar">
      <div
        class="progress-fill"
        :class="{ complete: pct === 100 }"
        :style="{ width: pct + '%' }"
      />
    </div>
    <ChecklistItem
      v-for="item in checklist.items"
      :key="item.id"
      :item="item"
    />
  </div>
</template>

<style scoped>
.checklist {
  margin-top: 10px;
}

.checklist-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 6px;
}

.checklist-title {
  font-size: 11px;
  font-weight: 600;
  color: #6b7280;
}

.checklist-count {
  font-size: 11px;
  color: #9ca3af;
}

.progress-bar {
  height: 3px;
  background: #e5e7eb;
  border-radius: 2px;
  margin-bottom: 6px;
  overflow: hidden;
}

.progress-fill {
  height: 100%;
  background: #6366f1;
  border-radius: 2px;
  transition: width 0.2s;
}

.progress-fill.complete {
  background: #10b981;
}
</style>
