// demo-vue-app/src/components/BoardView.vue
<script setup>
import BoardHeader from './BoardHeader.vue';
import Column from './Column.vue';
import { columns } from '../data/boardData';
</script>

<template>
  <div class="board-view">
    <BoardHeader />
    <div class="columns">
      <Column
        v-for="col in columns"
        :key="col.id"
        :column="col"
      />
    </div>
  </div>
</template>

<style scoped>
.board-view {
  flex: 1;
  padding: 24px;
  overflow: auto;
}

.columns {
  display: flex;
  gap: 16px;
  align-items: flex-start;
}
</style>

// demo-react-app/src/components/BoardView.jsx
import BoardHeader from './BoardHeader';
import Column from './Column';
import { columns } from '../data/boardData';

export default function BoardView() {
  return (
    <div style={{
      flex: 1,
      padding: '24px',
      overflow: 'auto',
    }}>
      <BoardHeader />
      <div style={{
        display: 'flex',
        gap: '16px',
        alignItems: 'flex-start',
      }}>
        {columns.map(col => (
          <Column key={col.id} column={col} />
        ))}
      </div>
    </div>
  );
}
