// demo-vue-app/src/components/ColumnHeader.vue
<script setup>
defineProps({
  title: String,
  count: Number,
});
</script>

<template>
  <div class="column-header">
    <span class="column-title">{{ title }}</span>
    <span class="column-count">{{ count }}</span>
  </div>
</template>

<style scoped>
.column-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12px;
  padding: 0 4px;
}

.column-title {
  font-size: 13px;
  font-weight: 600;
  color: #374151;
}

.column-count {
  font-size: 12px;
  color: #9ca3af;
  background: #e5e7eb;
  border-radius: 10px;
  padding: 1px 8px;
  font-weight: 500;
}
</style>

// demo-react-app/src/components/ColumnHeader.jsx
export default function ColumnHeader({ title, count }) {
  return (
    <div style={{
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: '12px',
      padding: '0 4px',
    }}>
      <span style={{
        fontSize: '13px',
        fontWeight: 600,
        color: '#374151',
      }}>
        {title}
      </span>
      <span style={{
        fontSize: '12px',
        color: '#9ca3af',
        background: '#e5e7eb',
        borderRadius: '10px',
        padding: '1px 8px',
        fontWeight: 500,
      }}>
        {count}
      </span>
    </div>
  );
}
