// demo-vue-app/src/components/Sidebar.vue
<script setup>
import ProjectItem from './ProjectItem.vue';
import { projects } from '../data/boardData';
</script>

<template>
  <aside class="sidebar">
    <div class="section-label">Projects</div>
    <ProjectItem
      v-for="p in projects"
      :key="p.id"
      :project="p"
    />
  </aside>
</template>

<style scoped>
.sidebar {
  width: 240px;
  background: #1b1f2e;
  padding: 20px 16px;
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.section-label {
  font-size: 11px;
  font-weight: 600;
  color: #6b7280;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  padding: 0 12px;
  margin-bottom: 8px;
}
</style>

// demo-react-app/src/components/Sidebar.jsx
import ProjectItem from './ProjectItem';
import { projects } from '../data/boardData';

export default function Sidebar() {
  return (
    <aside style={{
      width: '240px',
      background: '#1b1f2e',
      padding: '20px 16px',
      display: 'flex',
      flexDirection: 'column',
      gap: '4px',
    }}>
      <div style={{
        fontSize: '11px',
        fontWeight: 600,
        color: '#6b7280',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
        padding: '0 12px',
        marginBottom: '8px',
      }}>
        Projects
      </div>
      {projects.map(p => (
        <ProjectItem key={p.id} project={p} />
      ))}
    </aside>
  );
}
